//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HFVExplorer.rc
//
#define IDOKALL                         3
#define IDC_FILETYPE_IMPORT             3
#define IDC_FILETYPE_EXPORT             4
#define IDC_FILETYPE_NEW                5
#define IDC_FILETYPE_DELETE             6
#define IDC_FILETYPE_SELECT_ALL         7
#define IDC_FILETYPE_EXPORT_SELECTED    8
#define IDC_FILETYPE_SELECT_ALL2        9
#define IDC_FILETYPE_DUPLICATE          10
#define IDD_ABOUTBOX                    100
#define IDC_POINTER                     104
#define IDC_POINTER_COPY                105
#define IDR_MAINFRAME                   128
#define IDR_HFVEXPTYPE                  129
#define IDR_MAINFRAME_SAVE              129
#define IDI_ICON1                       130
#define IDI_ICON2                       131
#define IDI_ICON3                       132
#define IDI_ICON4                       133
#define IDI_ICON5                       134
#define IDD_OPTIONS_PAGE_1              134
#define IDD_OPTIONS_PAGE_2              135
#define IDI_ICON6                       135
#define IDD_OPTIONS_PAGE_3              136
#define IDI_ICON7                       136
#define IDI_ICON8                       137
#define IDD_OPTIONS_PAGE_4              137
#define IDD_OPTIONS_PAGE_5              138
#define IDD_OPTIONS_PAGE_6              139
#define IDI_ICON12                      141
#define IDI_ICON51                      142
#define IDI_ICON52                      143
#define IDB_BITMAP1                     143
#define IDI_ICON53                      144
#define IDI_ICON54                      145
#define IDI_ICON55                      146
#define IDI_ICON9                       147
#define IDI_ICON10                      148
#define IDI_ICON11                      149
#define IDI_ICON13                      150
#define IDD_ASK_NEW_DIR                 151
#define IDD_ASK_NEW_VOLUME              152
#define testi                           152
#define IDD_VOLUME_TO_FLOPPY            153
#define IDI_ICON1_YELLOW                153
#define IDI_ICON4_YELLOW                154
#define IDI_ICON51_YELLOW               155
#define IDD_ASK_DUMP                    156
#define IDI_ICON52_YELLOW               156
#define IDD_HFS_ITEM_PROPERTIES         157
#define IDI_ICON53_YELLOW               157
#define IDI_ICON54_YELLOW               158
#define IDD_DYNAMIC_COPYMODE_SELECT     159
#define IDI_ICON55_YELLOW               159
#define IDI_LABEL_PROJECT_2             160
#define IDI_LABEL_PROJECT_1             161
#define IDD_FILETYPE_MAPPINGS           162
#define IDI_LABEL_PERSONAL              162
#define IDD_OPTIONS_PAGE_7              163
#define IDI_LABEL_COOL                  163
#define IDD_OPTIONS_PAGE_8              164
#define IDI_LABEL_IN_PROGRESS           164
#define IDI_LABEL_HOT                   165
#define IDD_OPTIONS_PAGE_9              166
#define IDI_LABEL_ESSENTIAL             166
#define IDI_ICON56                      167
#define IDD_OPTIONS_PAGE_10             167
#define IDI_ICON56_YELLOW               168
#define IDC_OPTIONS_IS_FONT_SJIS        999
#define IDC_OPTIONS_MOUNT_ALL           1000
#define IDC_EXECUTOR_LIST               1001
#define IDC_OPTIONS_SAVE_SETTINGS       1001
#define IDC_OPTIONS_PATCH               1001
#define IDC_OPTIONS_SHOW_INVISIBLES     1002
#define IDC_OPTIONS_SHOW_INVISIBLES2    1003
#define IDC_EXECUTOR_VERSION            1004
#define IDC_OPTIONS_STARTUP_FLOPPIES    1004
#define IDC_EXECUTOR_SPLASH             1005
#define IDC_OPTIONS_STARTUP_CDS         1005
#define IDC_EXECUTOR_EXTRA              1006
#define IDC_OPTIONS_STARTUP_HDS         1006
#define IDC_EXECUTOR_DEFAULT            1007
#define IDC_EXECUTOR_ADD                1008
#define IDC_EXECUTOR_DELETE             1009
#define IDC_EXECUTOR_PATH               1011
#define IDC_EXECUTOR_BROWSE             1012
#define IDC_LIST1                       1013
#define IDC_EDIT1                       1014
#define IDC_EDIT2                       1015
#define IDC_PROP_PARENTID               1016
#define IDC_COPT4_VMAC_PATH             1016
#define IDC_FILETYPE_CREATOR            1016
#define IDC_COPT7_VMAC_PATH             1016
#define IDC_COMBO1                      1017
#define IDC_DOSICONS                    1017
#define IDC_PROP_CREATED                1017
#define IDC_COPT4_DEFAULT_EMULATOR      1017
#define IDC_NEW_DIR_NAME                1018
#define IDC_PROP_MODIFIED               1018
#define IDC_COPT4_VMAC_SYSTEM_FILE_PATH 1018
#define IDC_FONT                        1018
#define IDC_COPT9_FUSION_SYSTEM_FILE_PATH 1018
#define IDC_VOLNAME_BROWSE              1019
#define IDC_PROP_BACKUP                 1019
#define IDC_PSIZE                       1019
#define IDC_COPT9_FUSION_BATCH_PATH     1019
#define IDC_VOLNAME                     1020
#define IDC_PROP_X                      1020
#define IDC_PROP_Y                      1021
#define IDC_PROP_RSIZE                  1022
#define IDD_STATIC                      1023
#define IDC_PROP_DSIZE                  1023
#define IDC_PROP_TYPE                   1024
#define IDC_VOLSIZE_EX                  1025
#define IDC_PROP_CREATOR                1025
#define IDC_VOLPATH                     1026
#define IDC_PROP_VALENCE                1026
#define IDC_DUMP_TO_FLOPPY              1027
#define IDC_BROWSE_DUMP                 1028
#define IDC_DUMP_PATH                   1029
#define IDC_DUMP_START                  1030
#define IDC_PROP_ISDIR                  1030
#define IDC_DUMP_BLOCKS                 1031
#define IDC_PROP_ISINDESKTOP            1031
#define IDC_PROP_HASCOLORS              1032
#define IDC_PROP_RESERVEDCOLORS         1033
#define IDC_PROP_REQSWITCHLAUNCH        1034
#define IDC_PROP_ISSHARED               1035
#define IDC_PROP_HASNOINITS             1036
#define IDC_PROP_HASBEENINITED          1037
#define IDC_PROP_RESERVED               1038
#define IDC_PROP_HASCUSTOMICONS         1039
#define IDC_PROP_ISSTATIONERY           1040
#define IDC_PROP_ISNAMELOCKED           1041
#define IDC_PROP_HASBUNDLE              1042
#define IDC_PROP_ISINVISIBLE            1043
#define IDC_PROP_ISALIAS                1044
#define IDC_PROP_TOP                    1045
#define IDC_PROP_LEFT                   1046
#define IDC_PROP_BOTTOM                 1047
#define IDC_PROP_RIGHT                  1048
#define IDC_PROP_NAME                   1049
#define IDC_PROP_NODEID                 1050
#define IDC_PROP_ISLOCKED               1052
#define IDC_COPYOUT_MODE                1052
#define IDC_COPYIN_MODE                 1053
#define IDC_COPYIN_APPLEDOUBLE          1054
#define IDC_COPY_MODE                   1055
#define IDC_COPYING_FNAME               1056
#define IDC_FAT_ICON_TIME_LIMIT         1057
#define IDC_SHOW_INVISIBLE_MAC          1058
#define IDC_SHOW_INVISIBLE_PC           1059
#define IDC_COPT4_EXECUTOR_DOS_PATH     1059
#define IDC_PROTECT_LOCKED_MAC          1060
#define IDC_COPT4_EXECUTOR_WIN32_PATH   1060
#define IDC_COPT6_EXECUTOR_WIN32_PATH   1060
#define IDC_PROTECT_LOCKED_PC           1061
#define IDC_COPT4_BROWSE_EXECUTOR_DOS_PATH 1061
#define IDC_COPT4_BROWSE_EXECUTOR_WIN32_PATH 1062
#define IDC_COPT6_BROWSE_EXECUTOR_WIN32_PATH 1062
#define IDC_COPT4_BROWSE_VMAC_PATH      1063
#define IDC_COPT7_BROWSE_VMAC_PATH      1063
#define IDC_COPT4_BROWSE_VMAC_SYSTEM_FILE_PATH 1064
#define IDC_COPT9_BROWSE_FUSION_SYSTEM_FILE_PATH 1064
#define IDC_COPT4_BROWSE_VMAC_STARTUP_FOLDER_NAME 1065
#define IDC_COPT9_BROWSE_FUSION_STARTUP_FOLDER_NAME 1065
#define IDC_COPT4_VMAC_STARTUP_FOLDER_NAME 1066
#define IDC_COPT9_FUSION_STARTUP_FOLDER_NAME 1066
#define IDC_COPT4_VMAC_INSTALL          1067
#define IDC_COPT7_VMAC_INSTALL          1067
#define IDC_COPT9_BROWSE_FUSION_BATCH_PATH 1067
#define IDC_COPT4_LINK_NAME_STYLE       1069
#define IDC_COPT4_LAUNCH_METHOD         1070
#define IDC_COPT7_LAUNCH_METHOD         1070
#define IDC_FILETYPE_LIST               1071
#define IDC_FILETYPE_HFS2FAT            1072
#define IDC_FILETYPE_FAT2HFS            1073
#define IDC_FILETYPE_DOS                1074
#define IDC_FILETYPE_TYPE               1075
#define IDC_FILETYPE_ENABLED            1076
#define IDC_COPY_MAP                    1077
#define IDC_FILETYPE_COMMENT            1077
#define IDC_FILETYPE_STRIP              1078
#define IDC_FILETYPE_HELP               1079
#define IDC_FILETYPE_CONFLICT           1080
#define IDC_COPT5_EXECUTOR_DOS_PATH     1081
#define IDC_COPT5_BROWSE_EXECUTOR_DOS_PATH 1082
#define IDC_COPT7_VMAC_SYSTEM_FILE_PATH 1083
#define IDC_COPT7_VMAC_STARTUP_FOLDER_NAME 1084
#define IDC_COPT7_BROWSE_VMAC_SYSTEM_FILE_PATH 1085
#define IDC_COPT7_BROWSE_VMAC_STARTUP_FOLDER_NAME 1086
#define IDC_COPT8_SHAPESHIFTER_PATH     1087
#define IDC_COPT8_SHAPESHIFTER_SYSTEM_FILE_PATH 1088
#define IDC_COPT8_SHAPESHIFTER_STARTUP_FOLDER_NAME 1089
#define IDC_COPT8_BROWSE_SHAPESHIFTER_PATH 1090
#define IDC_COPT8_BROWSE_SHAPESHIFTER_SYSTEM_FILE_PATH 1091
#define IDC_COPT8_BROWSE_SHAPESHIFTER_STARTUP_FOLDER_NAME 1092
#define IDC_COPT8_SHAPESHIFTER_PREFERENCES_FILE_PATH 1093
#define IDC_USE_REMOVER                 1093
#define IDC_COPT8_BROWSE_SHAPESHIFTER_PREFERENCES_FILE_PATH 1094
#define IDC_COPT9_FUSION_USE_REMOVER    1094
#define IDC_COPT8_SHAPESHIFTER_AMIGA_VOLUME_NAME 1095
#define IDC_COPT10_HPBURNER_PATH        1095
#define IDC_COPT8_BROWSE_SHAPESHIFTER_AMIGA_VOLUME_NAME 1096
#define IDC_COPT10_HPBURNER_BROWSE      1096
#define IDC_COPT8_SHAPESHIFTER_USE_REMOVER 1097
#define ID_VIEW_LARGEICONS              32772
#define ID_VIEW_SMALLICONS              32773
#define ID_VIEW_LIST                    32774
#define ID_VIEW_DETAILS                 32775
#define ID_VIEW_OPTIONS                 32776
#define ID_VIEW_REFRESH                 32777
#define ID_TOOLS_FIND                   32778
#define ID_TOOLS_NEW_BROWSER            32784
#define ID_FILE_NEWVOLUME               32786
#define ID_FILE_VOLUMETOFLOPPY          32787
#define ID_FILE_VOLUMEFROMFLOPPY        32788
#define ID_TOOLS_DUMPCDDEBUG            32789
#define ID_CD_EJECT_RELOAD              32790
#define ID_CD_EJECT_EJECT               32791
#define ID_EDIT_LABEL                   32792
#define ID_VIEW_MAC_WINDOW              32795
#define ID_EDIT_COPY_APPEND             32800
#define ID_EDIT_CUT_APPEND              32801
#define ID_FILE_EJECT                   32802
#define ID_FILE_RELOAD                  32803
#define ID_TOOLS_BURN                   32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
